// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	journal "DHBW_Golang_Project/pkg/journal"

	mock "github.com/stretchr/testify/mock"
)

// Journal is an autogenerated mock type for the Journal type
type Journal struct {
	mock.Mock
}

// LogIn provides a mock function with given fields: cred
func (_m *Journal) LogIn(cred *journal.Credentials) bool {
	ret := _m.Called(cred)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*journal.Credentials) bool); ok {
		r0 = rf(cred)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LogOut provides a mock function with given fields: cred
func (_m *Journal) LogOut(cred *journal.Credentials) bool {
	ret := _m.Called(cred)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*journal.Credentials) bool); ok {
		r0 = rf(cred)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
