package main

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestDateValidator(t *testing.T) {
	res, _ := validateDateInput("111-01-01")
	assert.False(t, res)
	res, _ = validateDateInput("2021-13-01")
	assert.False(t, res)
	res, _ = validateDateInput("2021-10-32")
	assert.False(t, res)
	res, _ = validateDateInput("2021-10-13")
	assert.True(t, res)
	res, _ = validateDateInput("2021.10.13")
	assert.False(t, res)
	res, _ = validateDateInput("2021/10/13")
	assert.False(t, res)
	res, _ = validateDateInput("2021-10-22")
	assert.True(t, res)
}

func TestOperationValidator(t *testing.T) {
	res, _ := validateOperationInput("")
	assert.False(t, res)
	res, _ = validateOperationInput("a")
	assert.False(t, res)
	res, _ = validateOperationInput("A")
	assert.False(t, res)
	res, _ = validateOperationInput("0")
	assert.False(t, res)
	res, _ = validateOperationInput("3")
	assert.False(t, res)
	res, _ = validateOperationInput("11")
	assert.False(t, res)
	res, _ = validateOperationInput("01")
	assert.False(t, res)
	res, _ = validateOperationInput("1")
	assert.True(t, res)
	res, _ = validateOperationInput("2")
	assert.True(t, res)
}

func TestYesNoValidator(t *testing.T){
	res, _ := validateYesNoInput("")
	assert.False(t, res)
	res, _ = validateYesNoInput("something")
	assert.False(t, res)
	res, _ = validateYesNoInput("yess")
	assert.False(t, res)
	res, _ = validateYesNoInput("noo")
	assert.False(t, res)
	res, _ = validateYesNoInput("0")
	assert.False(t, res)
	res, _ = validateYesNoInput("1")
	assert.False(t, res)
	res, _ = validateYesNoInput("es")
	assert.False(t, res)
	res, _ = validateYesNoInput("o")
	assert.False(t, res)
	res, _ = validateYesNoInput("n")
	assert.True(t, res)
	res, _ = validateYesNoInput("Y")
	assert.True(t, res)
	res, _ = validateYesNoInput("N")
	assert.True(t, res)
	res, _ = validateYesNoInput("Yes")
	assert.True(t, res)
	res, _ = validateYesNoInput("No")
	assert.True(t, res)
	res, _ = validateYesNoInput("yes")
	assert.True(t, res)
	res, _ = validateYesNoInput("no")
	assert.True(t, res)
	res, _ = validateYesNoInput("yEs")
	assert.True(t, res)
	res, _ = validateYesNoInput("nO")
	assert.True(t, res)
}
